"""
Input validators for TestForge AI.

Validates Java source files, sizes, and file types.
"""
from __future__ import annotations

import os

from app.config import get_settings

settings = get_settings()

_ALLOWED_JAVA_EXTENSIONS = {".java"}
_EXPLICIT_REJECTED_EXTENSIONS = {".exe", ".zip", ".jar", ".py", ".js", ".class", ".sh", ".bat", ".cmd", ".bin", ".tar", ".gz"}


def validate_java_filename(file_name: str) -> None:
    """
    Validate that a file name has a .java extension and is not an unsupported binary or script.

    Raises:
        ValueError: If the file name is invalid.
    """
    if not file_name or not file_name.strip():
        raise ValueError("File name cannot be empty")

    ext = os.path.splitext(file_name.strip().lower())[1]
    if ext in _EXPLICIT_REJECTED_EXTENSIONS:
        raise ValueError(
            f"Unsupported file type '{ext}'. Only Java source files (.java) are accepted."
        )

    if ext not in _ALLOWED_JAVA_EXTENSIONS:
        raise ValueError(
            f"Only Java source files (.java) are accepted. Got: {ext!r}"
        )

    # Prevent path traversal
    basename = os.path.basename(file_name)
    if basename != file_name.strip():
        raise ValueError("File name must not contain path separators")


def validate_source_size(source_code: str) -> None:
    """
    Validate that source code is within the allowed 5 MB size limit.

    Raises:
        ValueError: If the source code is too large or empty.
    """
    max_size = get_settings().JAVA_MAX_SOURCE_SIZE_BYTES
    size = len(source_code.encode("utf-8"))
    if size > max_size:
        raise ValueError(
            f"Source code too large: {size} bytes. Maximum allowed: {max_size} bytes (5 MB)."
        )
    if not source_code.strip():
        raise ValueError("Source code cannot be empty")


def validate_prompt_size(prompt: str, max_chars: int | None = None) -> None:
    """Validate that a prompt is within the allowed size."""
    max_c = max_chars or settings.AI_MAX_PROMPT_CHARS
    if len(prompt) > max_c:
        raise ValueError(
            f"Prompt too large: {len(prompt)} characters. Maximum: {max_c}."
        )


def validate_provider_name(provider: str) -> None:
    """Validate that a provider name is recognized."""
    valid = {"gemini", "openrouter", "agentrouter"}
    if provider.lower() not in valid:
        raise ValueError(
            f"Unknown provider: {provider!r}. Valid providers: {', '.join(sorted(valid))}"
        )


def sanitize_test_code(test_code: str | None) -> str:
    """
    Remove markdown code fences from AI-generated test code.
    If the LLM output was truncated mid-method, trims the incomplete method
    and ensures class closing braces are balanced.
    """
    if not test_code:
        return ""
    lines = test_code.strip().splitlines()

    # Remove opening fence
    if lines and lines[0].strip().startswith("```"):
        lines = lines[1:]

    # Remove closing fence
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]

    code = "\n".join(lines).strip()

    # Balance unclosed braces if output was cut off mid-method
    open_b = code.count("{")
    close_b = code.count("}")
    if open_b > close_b:
        last_close = code.rfind("}")
        if last_close > 0:
            trimmed = code[:last_close + 1]
            t_open = trimmed.count("{")
            t_close = trimmed.count("}")
            if t_open > t_close:
                code = trimmed + ("\n}" * (t_open - t_close))
            else:
                code = trimmed
        else:
            code = code + ("\n}" * (open_b - close_b))

    return code


def validate_test_output(test_code: str | None) -> tuple[bool, str | None]:
    """
    Validate AI-generated JUnit test code.

    Checks:
    - Non-empty output
    - JUnit imports (org.junit.jupiter.* or org.junit.*)
    - Java class declaration (e.g. class FooTest or public class FooTest)
    - @Test annotation usage
    - Java-like syntax (braces balance, class structure)

    Returns:
        tuple[bool, str | None]: (True, None) if valid, (False, failure_reason) otherwise.
    """
    import re

    if not test_code or not test_code.strip():
        return False, "Empty output generated by AI model"

    code = test_code.strip()

    if len(code) < 20:
        return False, "Generation output is too short to be a valid Java test class"

    # 1. JUnit imports
    has_junit_import = bool(
        re.search(r"\bimport\s+(?:static\s+)?org\.junit\b", code)
        or re.search(r"\bimport\s+(?:static\s+)?junit\b", code)
    )
    if not has_junit_import:
        return False, "Missing JUnit imports (expected org.junit.jupiter.* or org.junit.*)"

    # 2. Class declaration
    has_class_decl = bool(
        re.search(r"\b(?:public\s+|final\s+|abstract\s+)*class\s+[A-Za-z0-9_]+", code)
    )
    if not has_class_decl:
        return False, "Missing Java class declaration"

    # 3. @Test usage
    has_test_annotation = bool(
        re.search(r"@(?:[A-Za-z0-9_.]+\.)?Test\b", code)
    )
    if not has_test_annotation:
        return False, "Missing @Test annotation"

    # 4. Java-like syntax: basic checks (braces balance, non-zero braces)
    open_braces = code.count("{")
    close_braces = code.count("}")
    if open_braces == 0 or close_braces == 0:
        return False, "Invalid Java syntax: missing class or method body braces"
    if open_braces != close_braces:
        return False, f"Invalid Java syntax: unbalanced curly braces ({open_braces} open, {close_braces} closed)"

    return True, None

