"""phase3_source_analyses

Revision ID: c01dbe0c94d3
Revises: 092f353d7da2
Create Date: 2026-09-21 15:36:36.869132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c01dbe0c94d3'
down_revision: Union[str, Sequence[str], None] = '092f353d7da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_analyses_id'), 'source_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_source_analyses_project_id'), 'source_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_source_analyses_source_file_id'), 'source_analyses', ['source_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_analyses_source_file_id'), table_name='source_analyses')
    op.drop_index(op.f('ix_source_analyses_project_id'), table_name='source_analyses')
    op.drop_index(op.f('ix_source_analyses_id'), table_name='source_analyses')
    op.drop_table('source_analyses')
    # ### end Alembic commands ###
